import type { ModelInfo } from "../model.js"

// https://brainiall.com
export type BrainiallModelId = keyof typeof brainiallModels

export const brainiallDefaultModelId: BrainiallModelId = "claude-sonnet-4-6"

export const brainiallModels = {
	"claude-opus-4-6": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 5.0,
		outputPrice: 25.0,
		cacheWritesPrice: 6.25,
		cacheReadsPrice: 0.5,
		description: "Claude Opus 4.6",
	},
	"claude-sonnet-4-6": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 3.0,
		outputPrice: 15.0,
		cacheWritesPrice: 3.75,
		cacheReadsPrice: 0.3,
		description: "Claude Sonnet 4.6",
	},
	"claude-haiku-4-5": {
		maxTokens: 8192,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 1.0,
		outputPrice: 5.0,
		cacheWritesPrice: 1.25,
		cacheReadsPrice: 0.1,
		description: "Claude Haiku 4.5",
	},
	"claude-opus-4-5": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBudget: true,
		inputPrice: 15.0,
		outputPrice: 75.0,
		description: "Claude Opus 4.5",
	},
	"deepseek-r1": {
		maxTokens: 64_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		preserveReasoning: true,
		inputPrice: 1.35,
		outputPrice: 5.4,
		description: "DeepSeek R1",
	},
	"deepseek-v3": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsPromptCache: false,
		inputPrice: 0.27,
		outputPrice: 1.1,
		description: "DeepSeek V3.2",
	},
	"llama-3.3-70b": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsPromptCache: false,
		inputPrice: 0.72,
		outputPrice: 0.72,
		description: "Meta Llama 3.3 70B",
	},
	"llama-4-scout": {
		maxTokens: 8192,
		contextWindow: 512_000,
		supportsPromptCache: false,
		inputPrice: 0.17,
		outputPrice: 0.17,
		description: "Meta Llama 4 Scout 17B",
	},
	"nova-pro": {
		maxTokens: 5120,
		contextWindow: 300_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.8,
		outputPrice: 3.2,
		description: "Amazon Nova Pro",
	},
	"nova-lite": {
		maxTokens: 5120,
		contextWindow: 300_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.06,
		outputPrice: 0.24,
		description: "Amazon Nova Lite",
	},
	"nova-micro": {
		maxTokens: 5120,
		contextWindow: 300_000,
		supportsPromptCache: false,
		inputPrice: 0.04,
		outputPrice: 0.14,
		description: "Amazon Nova Micro",
	},
	"mistral-large-3": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 2.0,
		outputPrice: 6.0,
		description: "Mistral Large 3 675B",
	},
	"devstral-2": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 1.5,
		description: "Devstral 2 123B",
	},
	"qwen3-80b": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 0.5,
		description: "Qwen3 80B",
	},
	"qwen3-32b": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsPromptCache: false,
		inputPrice: 0.35,
		outputPrice: 0.35,
		description: "Qwen3 32B",
	},
	"minimax-m2": {
		maxTokens: 16_384,
		contextWindow: 1_000_000,
		supportsPromptCache: false,
		inputPrice: 1.0,
		outputPrice: 5.0,
		description: "MiniMax M2",
	},
	"kimi-k2.5": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsPromptCache: false,
		inputPrice: 0.6,
		outputPrice: 2.4,
		description: "Moonshot Kimi K2.5",
	},
	"gpt-oss-120b": {
		maxTokens: 16_384,
		contextWindow: 200_000,
		supportsPromptCache: false,
		inputPrice: 1.35,
		outputPrice: 5.4,
		description: "GPT OSS 120B",
	},
} as const satisfies Record<string, ModelInfo>
