export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/Jothi-333/Joe-Code",
	GITHUB_DISCUSSIONS: "https://github.com/Jothi-333/Joe-Code/discussions",
	DISCORD: "https://discord.gg/joecode",
	REDDIT: "https://reddit.com/r/JoeCode",
	X: "https://x.com/joecodeai",
	LINKEDIN: "https://www.linkedin.com/company/joe-code",
	TIKTOK: "https://www.tiktok.com/@joe.code",
	BLUESKY: "https://bsky.app/profile/joecode.bsky.social",
	YOUTUBE: "https://www.youtube.com/@JoeCodeYT",
	DOCUMENTATION: "https://docs.joe-code.dev",
	SLACK_DOCS: "https://docs.joe-code.dev/roo-code-cloud/slack-integration",
	CAREERS: "https://careers.joe-code.dev",
	ISSUES: "https://github.com/Jothi-333/Joe-Code/issues",
	FEATURE_REQUESTS: "https://github.com/Jothi-333/Joe-Code/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/Jothi-333/Joe-Code/discussions",
	CHANGELOG: "https://github.com/Jothi-333/Joe-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/Jothi-333/Joe-Code/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.joe-code.dev/community",
	TUTORIALS: "https://docs.joe-code.dev/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=JoeCode.joe-code",
	SECURITY: "https://trust.joe-code.dev",
	EVALS: "https://joe-code.dev/evals",
	BLOG_SUBSTACK: "https://blog.joe-code.dev",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@JoeCodeYT/podcasts",
	FAQ: "https://joe-code.dev/#faq",
	TESTIMONIALS: "https://joe-code.dev/#testimonials",
	CLOUD_APP_LOGIN: "https://app.joe-code.dev/sign-in",
	CLOUD_APP_SIGNUP: "https://app.joe-code.dev/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.joe-code.dev/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.joe-code.dev/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.joe-code.dev/checkout/team",
	SUPPORT: "mailto:support@joe-code.dev",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
