name: Fork Issue
description: Create an issue to track changes made in this fork
title: "[Fork] "
labels: []
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the purpose of this fork and any planned changes
      placeholder: Type your description here...
    validations:
      required: true
