export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/JabberwockInc/Jabberwock",
	GITHUB_DISCUSSIONS: "https://github.com/JabberwockInc/Jabberwock/discussions",
	DISCORD: "https://discord.gg/jabberwock",
	REDDIT: "https://reddit.com/r/Jabberwock",
	X: "https://x.com/jabberwock",
	LINKEDIN: "https://www.linkedin.com/company/jabberwock",
	TIKTOK: "https://www.tiktok.com/@jabberwock.code",
	BLUESKY: "https://bsky.app/profile/jabberwock.bsky.social",
	YOUTUBE: "https://www.youtube.com/@JabberwockYT",
	DOCUMENTATION: "https://docs.jabberwock.com",
	SLACK_DOCS: "https://docs.jabberwock.com/jabberwock-cloud/slack-integration",
	CAREERS: "https://careers.jabberwock.com",
	ISSUES: "https://github.com/JabberwockInc/Jabberwock/issues",
	FEATURE_REQUESTS: "https://github.com/JabberwockInc/Jabberwock/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/JabberwockInc/Jabberwock/discussions",
	CHANGELOG: "https://github.com/JabberwockInc/Jabberwock/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/JabberwockInc/Jabberwock/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.jabberwock.com/community",
	TUTORIALS: "https://docs.jabberwock.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.jabberwock",
	SECURITY: "https://trust.jabberwock.com",
	EVALS: "https://jabberwock.com/evals",
	BLOG_SUBSTACK: "https://blog.jabberwock.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@JabberwockYT/podcasts",
	FAQ: "https://jabberwock.com/#faq",
	TESTIMONIALS: "https://jabberwock.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.jabberwock.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.jabberwock.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.jabberwock.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.jabberwock.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.jabberwock.com/checkout/team",
	SUPPORT: "mailto:support@jabberwock.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
