# Server:
# docker compose build web
# docker compose --profile server up

# Client:
# docker compose build runner
# docker compose up runner --no-start
# docker run -it --rm --network evals_default evals-runner bash
# docker run --rm --network evals_default evals-runner sh -c "pnpm --filter @roo-code/evals cli 3"

services:
    db:
        container_name: evals-db
        image: postgres:15.4
        ports:
            - 5432:5432
        volumes:
            - ./.docker/postgres:/var/lib/postgresql/data
            - ./.docker/scripts/postgres:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASES=evals_development,evals_test
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d evals_development"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 30s
        profiles:
            - server

    redis:
        container_name: evals-redis
        image: redis:7-alpine
        ports:
            - "6379:6379"
        volumes:
            - ./.docker/redis:/data
        command: redis-server --appendonly yes
        profiles:
            - server

    web:
        container_name: evals-web
        build:
            context: ../../
            dockerfile: packages/evals/Dockerfile.web
        ports:
            - "3000:3000"
        environment:
            - HOST_EXECUTION_METHOD=docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        user: "0:0" # Run as root to access docker socket.
        depends_on:
            db:
                condition: service_healthy
        profiles:
            - server

    runner:
        container_name: evals-runner
        build:
            context: ../../
            dockerfile: packages/evals/Dockerfile.runner
        stdin_open: true
        tty: true
        profiles:
            - client
