name: Auto-label Issues

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    name: Automatically label issues and PRs
    
    steps:
      - name: Label database issues
        if: contains(github.event.issue.title, 'database') || contains(github.event.issue.title, 'Database') || contains(github.event.issue.body, 'database')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['component/database']
            });
            
      - name: Label mobile issues
        if: contains(github.event.issue.title, 'mobile') || contains(github.event.issue.title, 'Mobile') || contains(github.event.issue.title, 'iOS') || contains(github.event.issue.title, 'Android')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['component/mobile']
            });
            
      - name: Label authentication issues
        if: contains(github.event.issue.title, 'auth') || contains(github.event.issue.title, 'Auth') || contains(github.event.issue.title, 'login') || contains(github.event.issue.title, 'security')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['component/auth']
            });
            
      - name: Label TASK epic issues
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body || '';
            
            if (title.includes('task-005') || title.includes('task 005')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['epic/task-005', 'component/mobile']
              });
            }
            
            if (title.includes('task-006') || title.includes('task 006')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['epic/task-006', 'component/auth']
              });
            }
            
            if (title.includes('task-007') || title.includes('task 007')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['epic/task-007', 'component/database']
              });
            }
            
            if (title.includes('task-008') || title.includes('task 008')) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['epic/task-008', 'component/mobile']
              });
            }
