name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (patch/minor/major)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate branch name
        id: branch
        run: |
          TIMESTAMP=$(date +%s)
          echo "name=release/v${{ github.event.inputs.version_type }}-$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "branch_name=release/v${{ github.event.inputs.version_type }}-$TIMESTAMP" >> "$GITHUB_OUTPUT"

      - name: Create release branch and bump version
        id: version
        run: |
          git checkout -b ${{ steps.branch.outputs.branch_name }}
          npm --no-git-tag-version version ${{ github.event.inputs.version_type }}
          VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT
          
          # Update CHANGELOG.md
          DATE=$(date +"%Y-%m-%d")
          echo -e "# v$VERSION ($DATE)\n\n## Changes\n\n- Release version $VERSION\n$(cat CHANGELOG.md)" > CHANGELOG.md
          
          git add package.json package-lock.json CHANGELOG.md
          git commit -m "Release v$VERSION"
          git tag -f "v$VERSION" -m "Release v$VERSION"
          git push --set-upstream origin ${{ steps.branch.outputs.branch_name }}
          git push --force --tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: release v${{ steps.version.outputs.new_version }}"
          body: |
            # Release v${{ steps.version.outputs.new_version }}
            
            This PR prepares a new release with the following changes:
            
            - Version bump to v${{ steps.version.outputs.new_version }}
            - Updated CHANGELOG.md
            - Created release tag
            
            ## After merging:
            - The package will be automatically published to npm
            - A GitHub release will be created with the changelog
            
            Please review the changes and approve if everything looks correct.
          branch: ${{ steps.branch.outputs.branch_name }}
          base: main
          delete-branch: true